//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GildedRose.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Inventory
    {
        public int Id { get; set; }
        public int PurchaseId { get; set; }
        public int InventoryId { get; set; }
        public int NumberOfItems { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
